architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = rootProject.project(":common-core").file("src/main/resources/${rootProject.mod_id}.accesswidener")
    mixin { useLegacyMixinAp = true }
}

apply from: rootProject.file("gradle/scripts/platform.gradle")

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

    implementation(files(project(":fabric-core").tasks.named("shadowJar")))

    common(project(path: ":testmod-common", configuration: "namedElements")) { transitive = false }
    shadowBundle project(path: ":testmod-common", configuration: "transformProductionFabric")
}