apply plugin: "maven-publish"

publishing {
    publications {
        maven(MavenPublication) {
            groupId = rootProject.maven_group
            artifactId = "${rootProject.archives_base_name}-${platform}"
            from components.java

            pom.withXml {
                def dependenciesNode = asNode().dependencies[0]
                if (dependenciesNode != null) {
                    dependenciesNode.dependency.findAll { dep ->
                        dep.groupId.text() == rootProject.maven_group && dep.artifactId.text().startsWith("common-")
                    }.each { dep ->
                        dependenciesNode.remove(dep)
                    }
                }
            }
        }
    }

    repositories {
        maven {
            url = project.version.contains('-PR') ? 'https://maven.daqem.com/snapshots' : 'https://maven.daqem.com/releases'
            credentials {
                username = System.getenv("MAVEN_USER")
                password = System.getenv("MAVEN_PASS")
            }
        }
    }
}