plugins {
    id "java-library"
    id "dev.architectury.loom" version "1.13-SNAPSHOT" apply false
    id "architectury-plugin" version "3.4-SNAPSHOT"
    id "com.github.johnrengelman.shadow" version "8.1.1" apply false
    id "me.shedaniel.unified-publishing" version "0.1.+" apply false
}

architectury {
    minecraft = rootProject.minecraft_version
}

subprojects {
    if (project.name in ["common", "fabric", "neoforge"]) return

    apply plugin: "dev.architectury.loom"
    apply plugin: "architectury-plugin"

    apply from: rootProject.file("gradle/scripts/java.gradle")
    apply from: rootProject.file("gradle/scripts/dependencies.gradle")

    base {
        archivesName = "${rootProject.archives_base_name}-${project.name}"
    }

    loom {
        silentMojangMappingsLicense()
        accessWidenerPath = rootProject.project(":common-core").file("src/main/resources/${rootProject.mod_id}.accesswidener")
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings loom.layered() {
            officialMojangMappings()
            parchment("org.parchmentmc.data:parchment-${rootProject.parchment_version}@zip")
        }
    }
}

allprojects {
    group = rootProject.maven_group
    version = rootProject.mod_version

    task printVersionName {
        doLast {
            println version
        }
    }
}