org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon=false
java_version=25

# Project
group=com.daqem.knot
version=21.2.4
mod_id=knot
mod_name=Knot
mod_description=Tie Fabric and NeoForge together. Knot a problem.
mod_author=DAQEM
mod_license=LGPL-3.0
mod_website=https://daqem.com/projects/knot
mod_repository=https://github.com/DAQEM/Knot

# Publishing
supported_minecraft_versions=26.2
release_type=release
curse_forge_project_id=1470052
modrinth_project_id=V9WxBDCZ

# Dependencies
minecraft_version=26.2
neo_form_version=26.2-2
modmenu_version=20.0.1
fabric_permissions_api_version=0.7.0

# Fabric
fabric_version=0.156.0+26.2
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=26.2.0.37-beta