plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

apply from: rootProject.file("gradle/scripts/publishing.gradle")
apply from: rootProject.file("gradle/scripts/maven-publishing.gradle")

configurations {
    moduleJava { canBeResolved = true }
    moduleResources { canBeResolved = true }
}

neoForge {
    version = neoforge_version
    def at = project(':common-core').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()}"
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file("runs/client"))
        }
        server {
            server()
            this.file("runs/server").createParentDirectories()
            gameDirectory = this.mkdir(this.file("runs/server"))
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    def submodules = [
            ':common-api', ':common-core', ':common-networking', ':common-events', ':common-registry',
            ':neoforge-networking', ':neoforge-events', ':neoforge-registry'
    ]

    submodules.each { proj ->
        compileOnly(project(proj)) {
            attributes { attribute(Attribute.of('io.github.mcgradleconventions.loader', String), proj.startsWith(':common') ? 'common' : 'neoforge') }
        }
        moduleJava project(path: proj, configuration: 'moduleJava')
        moduleResources project(path: proj, configuration: 'moduleResources')
    }
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.moduleJava)
    source(configurations.moduleJava)
}

processResources {
    dependsOn(configurations.moduleResources)
    from(configurations.moduleResources)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.moduleJava)
    from(configurations.moduleJava)
    dependsOn(configurations.moduleResources)
    from(configurations.moduleResources)
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements'].each { variant ->
    configurations.named("$variant") { attributes { attribute(loaderAttribute, 'neoforge') } }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") { attributes { attribute(loaderAttribute, 'neoforge') } }
    }
}