plugins {
    id 'multiloader-common'
    id 'net.fabricmc.fabric-loom'
}

apply from: rootProject.file("gradle/scripts/publishing.gradle")
apply from: rootProject.file("gradle/scripts/maven-publishing.gradle")

configurations {
    moduleJava { canBeResolved = true }
    moduleResources { canBeResolved = true }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    compileOnly "com.terraformersmc:modmenu:${modmenu_version}"
    compileOnly "me.lucko:fabric-permissions-api:${fabric_permissions_api_version}"

    def submodules = [
            ':common-api', ':common-core', ':common-networking', ':common-events', ':common-registry',
            ':fabric-networking', ':fabric-events', ':fabric-registry'
    ]

    submodules.each { proj ->
        compileOnly(project(proj)) {
            attributes { attribute(Attribute.of('io.github.mcgradleconventions.loader', String), proj.startsWith(':common') ? 'common' : 'fabric') }
        }
        moduleJava project(path: proj, configuration: 'moduleJava')
        moduleResources project(path: proj, configuration: 'moduleResources')
    }
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.moduleJava)
    source(configurations.moduleJava)
}

processResources {
    dependsOn(configurations.moduleResources)
    from(configurations.moduleResources)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.moduleJava)
    from(configurations.moduleJava)
    dependsOn(configurations.moduleResources)
    from(configurations.moduleResources)
}

sourceSets {
    main {
        resources {
            srcDir project(':common-core').file('src/main/resources')
        }
    }
}

loom {
    def aw = project(':common-core').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") { attributes { attribute(loaderAttribute, 'fabric') } }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") { attributes { attribute(loaderAttribute, 'fabric') } }
    }
}