plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

configurations {
    moduleJava { canBeResolved = true }
    moduleResources { canBeResolved = true }
}

neoForge {
    version = neoforge_version

    // Pass the main mod's AT into the test environment so things compile and run smoothly
    def at = project(':common-core').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', "knot_test")
            ideName = "NeoForge Test ${it.name.capitalize()}"
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file("runs/client"))
        }
        data {
            serverData()
            gameDirectory = this.mkdir(this.file('runs/data'))
            programArguments.addAll(
                    '--mod', 'knot_test',
                    '--all',
                    '--output', rootProject.file('testmod-common/src/generated/resources').getAbsolutePath(),
                    '--existing', rootProject.file('testmod-common/src/main/resources').getAbsolutePath()
            )
        }
        server {
            server()
            this.file("runs/server").createParentDirectories()
            gameDirectory = this.mkdir(this.file("runs/server"))
        }
    }
    mods {
        "knot_test" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation project(':neoforge-core')

    compileOnly(project(':testmod-common')) {
        attributes { attribute(Attribute.of('io.github.mcgradleconventions.loader', String), 'common') }
    }
    moduleJava project(path: ':testmod-common', configuration: 'moduleJava')
    moduleResources project(path: ':testmod-common', configuration: 'moduleResources')

    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.moduleJava)
    source(configurations.moduleJava)
}

sourceSets {
    main {
        resources {
            srcDir rootProject.file('testmod-common/src/main/resources')
            srcDir rootProject.file('testmod-common/src/generated/resources')
        }
    }
}

processResources {
    dependsOn(configurations.moduleResources)
    from(configurations.moduleResources)
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements'].each { variant ->
    configurations.named("$variant") { attributes { attribute(loaderAttribute, 'neoforge') } }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") { attributes { attribute(loaderAttribute, 'neoforge') } }
    }
}