architectury {
    platformSetupLoomIde()
    neoForge {
        platformPackage = "neoforge"
    }
}

loom {
    accessWidenerPath = rootProject.project(":common-core").file("src/main/resources/${rootProject.mod_id}.accesswidener")
}

apply from: rootProject.file("gradle/scripts/platform.gradle")

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"

    implementation(files(project(":neoforge-core").tasks.named("shadowJar")))

    common(project(path: ":testmod-common", configuration: "namedElements")) { transitive = false }
    shadowBundle project(path: ":testmod-common", configuration: "transformProductionNeoForge")
}