plugins {
    id 'knot-submodule'
    id 'net.neoforged.moddev'
}

neoForge { version = neoforge_version }

dependencies {
    [':common-api', ':common-core', ':common-registry'].each {
        compileOnly(project(it)) {
            attributes { attribute(Attribute.of('io.github.mcgradleconventions.loader', String), 'common') }
        }
    }
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements'].each { variant ->
    configurations.named("$variant") { attributes { attribute(loaderAttribute, 'neoforge') } }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") { attributes { attribute(loaderAttribute, 'neoforge') } }
    }
}