modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPL-3.0"

[[mods]]
modId = "knot_test"
version = "1.0.0"
displayName = "Knot Test"
authors = "DAQEM"
description = '''
A test mod for the Knot library.
'''
